[project]
name = "stab-dkl"
version = "0.1.0"
requires-python = ">=3.10,<3.11"

dependencies = [
    "torch==2.7.1",
    "torchvision",
    "torchaudio",
    "torchmetrics",
    "gpytorch==1.14",
    "transformers==4.48.1",
    "pytorch-lightning",
    "numpy",
    "pandas",
    "pyyaml",
    "biopython",
    "tqdm",
    "joblib",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118" }
]
torchvision = [
  { index = "pytorch-cu118" }
]
torchaudio = [
  { index = "pytorch-cu118" }
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true